[package]
name = "multiplex-admin"
version = "0.0.2"
authors = ["Florian Anderiasch <fa@art-core.org>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
postgres = { version = "0.19.9", features = ["with-time-0_3"] }
time = "0.3.36"
